[profile.default]
  src = "contracts"
  out = "out"
  libs = ["node_modules", "lib"]
  test = "test"
  cache_path = "cache_forge"
  build_info = true
  extra_output = ["storageLayout"]
  via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
